apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx 
  name: nginx
spec:
  ports:
  - port: 80

  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: nginx
  type: LoadBalancer
